import Head from 'next/head'
import Banner from '../components/Banner'
import Header from '../components/Header'
import MediumCard from '../components/MediumCard';
import SmallCard from '../components/SmallCard';

export default function Home({exploreData,cardsData}) {
  return (
    <div>
      <Head>
        <title>leaflets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      {/* Banner */}
      <Banner />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">近くを探す</h2>
          {/* items */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-col-3 xl:grid-cols-4 ">
            {exploreData?.map(({ img, distance, location }) => (
              <SmallCard
                key={img}
                img={img}
                distance={distance}
                location={location}
              />
            ))}
          </div>
        </section>
        <section>
          <h2 className="text-4xl font-semibold py-8">
            次に行く旅のアイディアを見つけよう
          </h2>

          <div className="flex space-x-3 overflow-x-auto scrollbar-hide p-3 -ml-3">
            {/* //scrollbar-hide */}
            {cardsData?.map(({ img, title }) => (
              <MediumCard key={img} img={img} title={title} />
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch(
    'https://links.papareact.com/pyp'
  ).then(
    (res) => res.json()
  );

  const cardsData = await fetch('https://links.papareact.com/zp1')
    .then(res=>res.json());

  return {
    props: {
      exploreData,
      cardsData
    }
  }
}
